import './globals.css';
import Header from './header';
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<head>
				<title>AliAyubi.com</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<link rel='icon' href='/favicon.ico' />
			</head>
			<body className='bg-[#111]'>
				<Header />
				{children}
			</body>
		</html>
	);
}
